---
title: "ds202 lab 4"
author: "Connor Hergenreter"
date: "March 27, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Importing and Setting up Data

```{r}
library(tidyr)
library(dplyr)
library(readxl)
library(ggplot2)
defense <- read_excel('cyclonesFootball2018.xlsx', sheet='Defensive')
str(defense)
offensive <- read_excel('cyclonesFootball2018.xlsx', sheet='Offensive')
str(offensive)
biography <- read_excel('cyclonesFootball2018.xlsx', sheet='Biography')
str(biography)
```

#Part 1

```{r}
head(defense)
cols <- c("Name", "Opponent_Opponent")
colsdef <- c("Tackles_Solo", "Tackles_ASST", "Tackles_TFL", "Tackles_Sack", "Turnover_FF", "Turnover_FR", "Turnover_INT", "Pass_QBH", "Pass_PB")
colsoff <- c("Receiving_REC", "Receiving_YDS", "Receiving_TD", "Rushing_ATT", "Rushing_YDS", "Rushing_TD", "Passing_CMP-ATT", "Passing_YDS", "Passing_TD", "Passing_INT")
defense %>% mutate_at(cols, as.factor)
defClean <- defense %>% mutate_at(colsdef, as.numeric)
offensive %>% mutate_at(cols, as.factor)
offClean <- offensive %>% mutate_at(colsoff, as.numeric)
bioClean <- biography %>% mutate_at("Weight", as.numeric)
```

Something I wanted to check out was the tackles by weight. Using the scatterplot below it appears that the lighter defense players seem to pull in more tackles than the heavier ones. This shows another negative relationship with tackles by weight.

```{r}
defBio <- inner_join(defClean, bioClean, by="Name")

ggplot(defBio, aes(x=Weight, y=Tackles_Solo)) + geom_point() + labs(Title="Solo Tackles by Weight", x="Weight", y="Solo Tackles")
```